### ISSUE TITLE
Running Add Locale results in "Flutter Intl plugin detected invalid project structure" error

### ISSUE THREAD

**Issue by slimyjimmy** [localizely/flutter-intl-intellij#46]
Whenever I try to `Add Locale` or `Remove Locale`, Android Studio pops up a dialog saying "Flutter Intl plugin detected invalid project structure".
What am I doing wrong? I just downloaded the plugin and after that initialised the project (which I tried to do again, but the plugin wouldn't let me because "the plugin is already initialised").

Thanks in advance

**Comment by lzoran** [comment]
Hi @slimyjimmy,

Thanks for reporting this!

Could you provide us more info (operating system, flutter version, Android Studio version), so we could try to reproduce this issue on our machines?

Regarding the message _"Flutter Intl plugin detected invalid project structure"_, it looks like the plugin can't find a valid root of the project. Could you provide us more info regarding your "Modules" under "Project Structure" (`Ctrl+Alt+Shift+S`)?

![AS - Project Structure](https://user-images.githubusercontent.com/15170421/99587806-ede10d00-29e9-11eb-9aaa-c3d45b7f1268.png)

Have you tried to run our [sample app](https://github.com/localizely/flutter-intl-plugin-sample-app)? Do you encounter the same problem there?

After "Flutter Intl" plugin initialization, `pubspec.yaml` file of your project is extended with the `flutter_intl` configuration (see [General Usage Instructions](https://plugins.jetbrains.com/plugin/13666-flutter-intl) for more details). You can only initialize the "Flutter Intl" plugin when the `flutter_intl` section does not exist within `pubspec.yaml` file, or in the case when `enabled` is set to `false`.
```
flutter_intl:
  enabled: true # The plugin is initialized when this is set to true
```

**Comment by slimyjimmy** [comment]
Hi @lzoran !
Here's the output of flutter doctor on my machine: 

> [✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-DE)
>
>[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> 
>[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
>[✓] Android Studio (version 4.1)
>[!] VS Code (version 1.51.1)
>    ✗ Flutter extension not installed; install from
>      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
>[✓] Connected device (2 available)
>
>! Doctor found issues in 1 category.

Note, that I don't actually use VS Code, though. So the one issue flutter doc found, should really not be one..

As far as the structure of my project goes, I can't seem to find the dialog you showed in your screenshot (although I did try using the corresponding shortcut for Mac (Cmd + semicolon) which didn't seem to do anything unfortunately).

I just tried running your sample app and it works fine. One difference I noticed between the sample project and my project is how the root of the project is displayed in Android Studio. I'm not sure this is actually important to this issue but note how the root of the sample project shows a flutter logo while the root of my project doesn't.

![Screenshot of my project](https://user-images.githubusercontent.com/50664914/100078954-64e03080-2e44-11eb-87ed-a976096e2e95.png)

![Screenshot of the sample project](https://user-images.githubusercontent.com/50664914/100078988-70cbf280-2e44-11eb-9f85-87d3bd82a01f.png)

Thanks for your help!

**Comment by aleksakrstic** [comment]
Hi @slimyjimmy 
It is very possible that the root of the project is not associated with Flutter and that causing the issue.
If `CMD + ;` shortcut does not work for you, could you go to `File -> Project Structure...` and check it? 

If you do not find solution there, you can create a new Flutter project with `File -> New -> New Flutter Project...` and that newly project should should work fine with Flutter Intl plugin. Then you can compare what differs with your project and potentially fix it.

**Comment by slimyjimmy** [comment]
Hey there, so I compared the structure of your example project and my project and I noticed there were two "main" modules under Project Settings > Modules in my project. Removing one (the one, the example project lacked), however, didn't fix it and  so far I haven't really found anything else. 
Copying everything into a new project isn't really worth it for now, but I'm looking forward to a new project. In the meantime I'll just add locales manually I think.

Anyways, thanks for your help👍

**Comment by chanreylee** [comment]
May be the module name is without “_”, such as the origin module name is "haha", it may be caused this iussue.
when I try a new flutter project , the module is with "_", like "haha_flutter", it will be not alert this dialog, and it is normal

**Comment by wladimirguerra** [comment]
Hey guys!
I have the same issue. In my case I have a project with a Flutter module. When I try to `Add Location` I get the error. But if I close the project and open only the module the `Add Location` works as expected.

It seems that the plugin doesn't support a project with multiple modules. 
One solution would be that it could find the target module by checking what module is `selected` by the user in the `Project Files` or `Project` Tool window.

**Comment by deakjahn** [comment]
Could you help us with the description of what actually leads to this error message? I have two projects that, for whatever I can compare them for, seem pretty much identical in structure. One shows the error, the other does not. Compiling both projects works, the internationalization files are processed and the resulting apps both work perfectly. Still, there's the error in one of them.

Again, internationalization works in both. So, all your primary questions will be answered by yes:

- the `pubspec.yaml` files have the `flutter_intl: enabled: true` item;
- even in the project that shows the error on _Add Locale_, trying to initialize again from the menu says that it's already initialized for the project;
- both have a `l10n` folder with the language files, properly named, functioning;
- both have a `generated` folder where the generated files appear, properly, functioning;
- _Project Structure_ shows two modules the base one and the `_android` one;
- both projects happen to be Android-only, no `ios`, `web` or any desktop variant;
- both use Android SDK 31;
- both projects have the very same folder structure;

I'm running on Windows, latest AS Chipmunk, latest plugin (v 1.17.2).

**Comment by deakjahn** [comment]
@aleksakrstic My `idea.log` contains this entry:

```
2022-05-18 22:41:04,963 [5339552]   WARN - y.flutter.intl.utils.FileUtils - Failed to validate project structure 
java.lang.Exception: Unknown project base directory
	at com.localizely.flutter.intl.utils.FileUtils.getProjectBaseDir(FileUtils.java:147)
	at com.localizely.flutter.intl.utils.FileUtils.isProjectStructureValid(FileUtils.java:131)
	at com.localizely.flutter.intl.utils.PluginUtils.getIfPreparedAndShowMessage(PluginUtils.java:219)
	at com.localizely.flutter.intl.actions.FlutterIntlAddLocaleAction.actionPerformed(FlutterIntlAddLocaleAction.java:19)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:277)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:269)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
```

I'm also trying to track down other, possibly related issues with this project, namely that the log shows repeated "Project roots of XXX have changed" items, all without apparent reason. As these source files are not to be found here, could you say what makes the plugin think it doesn't know the base dir? The project has its proper root, of course, is a completely functioning Flutter project otherwise, compiles, runs, gets published on Google Play Store. Two modules, one main, one Android, as described in the previous post, it looks just like other similar projects to all intents and purposes.

**Comment by Mohammed-Amleh** [comment]
i faced this problem because of android studio capitalizing the first letter of your project name.

my Name of project was Go_and_bro -> after rename it to go_and_bro its works .

**Comment by nrmiller** [comment]
FWIW, I was able to fix this by recreating the IntelliJ .iml file.

I'm ignoring this file since I don't want others to depend on IntelliJ, but somehow the way it was generated/changed was incompatible with the plugin.
