### ISSUE TITLE
Plugin disabled automatically on Intellij Idea

### ISSUE THREAD

**Issue by kishor-mainali** [localizely/flutter-intl-intellij#89]
Intellij Version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Intl Version: 1.17.3-2020.3
OS Version:  macOs monterey 12.5.1

plugin automatically disabled in intellij idea

StackTrace:
`java.lang.ClassCastException: class lv.kid.vermut.intellij.yaml.psi.impl.NeonFileImpl cannot be cast to class org.jetbrains.yaml.psi.YAMLFile (lv.kid.vermut.intellij.yaml.psi.impl.NeonFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5ed208a6; org.jetbrains.yaml.psi.YAMLFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @69b09c1d)
	at com.localizely.flutter.intl.utils.PluginUtils.isPluginEnabledForProject(PluginUtils.java:77)
	at com.localizely.flutter.intl.actions.ExtractStringKeyAction.isAvailable(ExtractStringKeyAction.java:319)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:167)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:339)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:204)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:338)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:242)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
`

after enabling and tries to save files it gives error
The plugin com.localizely.flutter-intl failed to save settings and has been disabled. Please restart IntelliJ IDEA

**Comment by lzoran** [comment]
Hi @kishor-mainali,

Thanks for reporting this!

I've tried to reproduce this issue on Windows with the same config, but it seems that everything works OK. 
@aleksakrstic, could you try to reproduce this issue on macOS? 

Could you check if uninstalling and installing the Dart, Flutter, and Flutter Intl plugin help (maybe it is some issue related to the IDE upgrade)?

**Comment by aleksakrstic** [comment]
@kishor-mainali 
I just tried to reproduce but it worked fine.
Did restart of IntelliJ IDEA solved the issue for you?

**Comment by kishor-mainali** [comment]
@lzoran @aleksakrstic thanks for response i just reinstalled the IntelliJ IDEA and it works fine for me.
